### ISSUE TITLE
Crypto: Checksum hex encoding 

### ISSUE THREAD

**Issue by momipsl** [casper-network/casper-python-sdk#23]
New feature within node maps lower case publicKeyHex to checksumed hex.  This needs to be supported.

**Comment by ledgerleapllc** [comment]
I want to integrate a solution for this, but it's much different than EIP-55 (https://eips.ethereum.org/EIPS/eip-55).
I'm not a rust guy, so I'm having trouble converting the following code before finishing up.
`
fn bytes_to_bits_cycle(bytes: Vec<u8>) -> impl Iterator<Item = bool> {
    bytes
        .into_iter()
        .cycle()
        .flat_map(move |byte| (0..8usize).map(move |offset| ((byte >> offset) & 0x01) == 0x01))
}
`

**Comment by momipsl** [comment]
@ledgerleapllc am in process of implementing.

**Comment by momipsl** [comment]
@ledgerleapllc On dev branch I now have a functioning implementing of the CSPR checksum encoder/decoder plus associated unit tests.  Tomorrow I will endeavour to apply the checksumming as appropriate.

- https://github.com/casper-network/casper-python-sdk/blob/dev/pycspr/crypto/cl_checksum.py

**Comment by momipsl** [comment]
@ledgerleapllc v0.11.0 of pycspr has just been released upon pypi.  This includes full support for checksumming.

- https://github.com/casper-network/casper-python-sdk/blob/dev/pycspr/crypto/cl_checksum.py
