### ISSUE TITLE
QUERY: query_global_state not implemented

### ISSUE THREAD

**Issue by cnorburn** [casper-network/casper-python-sdk#27]
query_global_state needs implemented

**Comment by moubctez** [comment]
For me `query_global_state()` sends incorrect JSON-RPC which get rejected by the node. Currently the message looks more-or-less like this:

```
{
  "jsonrpc": "2.0",
  "method": "query_global_state",
  "params": {
    "state_identifier": {
      "StateRootHash": "…"
    },
    "key": {
      "Hash": "hash-…"
    },
    "path": null
  },
  "id": 5
}
```

The `key` should be formed as:

```
"key": "hash-…"
```

I had to apply the following patch to make it work:

```
--- pycspr/api/params.py.orig	2023-08-31 20:16:23.000000000 +0000
+++ pycspr/api/params.py
@@ -229,7 +229,7 @@ def get_query_global_state_params(
         "state_identifier": {
             state_id_type: state_id
         },
-        "key": serialisation.cl_value_to_parsed(key),
+        "key": key,
         "path": path
     }
 
```

**Comment by stormeye2000** [comment]
Further work on this reveals the problem:

The node is expecting JSON:

`{
    "id": "383766003",
    "jsonrpc": "2.0",
    "method": "query_global_state",
    "params": {
        "state_identifier": {
            "BlockHash": "042074ad78585bd077a0a669bb64f647bbd221f8e81997cadab59a54058e0ad6"
        },
        "key": "account-hash-98f380B97c33C4ea4a70B9Be7830fA59834E68Da8F2BBf17d2652fb22180aE19",
        "path": []
    }
}`

The SDK is passing both the 'state_identifier' and the 'key' as dict items

The parameters need to be set to string values, not dicts
