### ISSUE TITLE
Tests should not be installed

### ISSUE THREAD

**Issue by moubctez** [casper-network/casper-python-sdk#35]
Python module should not install tests in `site-packages/tests`. This patch fixes the problem:

```
--- setup.py.orig	2023-08-22 07:19:18.000000000 +0000
+++ setup.py
@@ -45,7 +45,7 @@ def _get_version():
 _VERSION = _get_version()
 
 # Library packages.
-_PACKAGES = find_packages()
+_PACKAGES = find_packages(exclude=['tests*'])
 
 # User readme.
 _README = _read("README.rst")
```

**Comment by asladeofgreen** [comment]
@moubctez Thank you for highlighting this.  Just pushed your suggested patch.  Probably moving to poetry fairly soon so things will change a little anyway, but regardless thx once again.
