### ISSUE TITLE
jsonrpcclient v4 causes some breaking changes

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/casper-python-sdk#4]
Since the jsonrpcclient v4 has some breaking changes the pycspr library needs to be updated.

Breaking changes:
https://composed.blog/jsonrpcclient-4-changes

I don't have the time right now to update all files but this is one example [PR](https://github.com/GuybrushX/casper-python-sdk/tree/patch-4)

**Comment by sisco0** [comment]
How should I configure my _localhost_ _Casper network_ so the next error would be fixed when running `pytest`?

![image](https://user-images.githubusercontent.com/25695302/133917042-bf80c3ae-ecc2-45d9-91f2-816d9cc89d72.png)
